### ISSUE TITLE
callout blocks is displayed in the wrong format

### ISSUE THREAD

**Issue by sonct988** [jonstodle/obsius-obsidian-plugin#10]
callout blocks is displayed in the wrong format. I hope you can make it look like on obsius

Link Publish: https://obsius.site/4u1p5z3c0g5w0i4h5s65

![CleanShot 2022-12-26 at 08 26 34@2x](https://user-images.githubusercontent.com/21117587/209488179-7292b357-5ea1-4dfe-b79a-ae279370b536.jpg)

**Comment by jonstodle** [comment]
It looks like Obsidian uses an uncommon syntax for this, and there's not direct support for that format in the renderer I use for Obsius. I could make my own implementation for this, but that would require an investment I can't promise at the moment. I might get back to this in the future.
