### ISSUE TITLE
Embed referenced attachments in the published documents

### ISSUE THREAD

**Issue by spc94** [jonstodle/obsius-obsidian-plugin#11]
Currently any attachments, such as pasted images show up in _obsius_ as "!Pasted image xyz.png". It would be incredibly helpful to send along the actual attachment and render it.

**Comment by Osurelee** [comment]
I have the same requirement, thank you for considering adding it

**Comment by jonstodle** [comment]
Adding support for images will be difficult to implement for a free service. I'm getting by at the moment on the fact that text is very space efficient, and therefore does not cost a lot to host.

Image support could be a future feature, but is not planned at the moment.
