### ISSUE TITLE
Site not rendering dataview table

### ISSUE THREAD

**Issue by crainbf** [jonstodle/obsius-obsidian-plugin#12]
I created a note with my work projects that I want to share with someone else using Obsius Publish. I'm using dataview to show all the projects and outcome. 

The query is:
`dataview
TABLE
FROM #project
WHERE !completed and contains(tags, "x")`

This is rendering fine in Obsidian, but on the website, it just shows the dataview code but doesn't render the content. 

Is that expected behavior? Is there some way to render data using dataview?

**Comment by jonstodle** [comment]
The Obsius plugin only transmits the raw markdown to the Obsius service, and only the markdown of the current document. Dataview relies on having access to your complete vault when rendering it's tables.

There are no plans of supporting multiple/linked documents on Obsius, or any features that relies on access to other documents in your vault.
