### ISSUE TITLE
Failing to update and remove notes 

### ISSUE THREAD

**Issue by crainbf** [jonstodle/obsius-obsidian-plugin#13]
This is for the same note that uses the dataview query mentioned in issue https://github.com/jonstodle/obsius-obsidian-plugin/issues/12. 

When I now click `update note in Obsius` it gives the error `failed to update note in Obsius`. 
When I click `remove note from Obsius` it gives `failed to remove note from Obsius`.

**Comment by jonstodle** [comment]
This should now be fixed in version 1.2.2
