### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by clehene** [jonstodle/obsius-obsidian-plugin#18]
Based on https://github.com/jonstodle/obsius-obsidian-plugin/issues/16 with no answers in 2 months, can we assume this is dead?
I think this could be useful.
I suggest trying to find contributors, but in the meantime it would help everyone save some time if this was removed from the obisidian plugins.

**Comment by jonstodle** [comment]
Hi! As you suspect this has been dormant for a while. I had some stuff I needed to work out, but I'm back now.

I've just published an update to the plugin which fixes the issue.

Thank you for interest and concern ❤️
