### ISSUE TITLE
Hide frontmatter and other hidden content

### ISSUE THREAD

**Issue by ashishbhateja** [jonstodle/obsius-obsidian-plugin#2]
Hi,

Thanks for this plugin. Is it possible to hide the note front matter and those enclosed under %%...%%.
Also, the backlinks show up as _[[backlink]]_, It will be good to suppress the additional formatting and show this as normal text.

**Comment by jonstodle** [comment]
Would you be able to share the link to published page?

**Comment by jonstodle** [comment]
There's a new release rolling out which hides front matter, removes content enclosed in `%%...%%`, and removes the `[[..]]` around internal links.
