### ISSUE TITLE
Could I see all my publishing notes using obsius in one place?

### ISSUE THREAD

**Issue by slowdive14** [jonstodle/obsius-obsidian-plugin#6]
Thanks for your effort. This plugin is so much useful. 

I'm curious that I can see all my publishing notes using obsius in one place.

Because I forget what note I published using obsius.

I'll wait for your comment.

**Comment by jonstodle** [comment]
It's not possible, but this seems like a good idea.

As a temporary workaround you can find the file where the plugin data is stored at this file path: `<your Obsidian vault>/.obsidian/plugins/obsius-publish/data.json` where `<your Obsidian vault` is the path to folder that you open as an Obsidian vault.

**Comment by jonstodle** [comment]
A command ("View published posts") has been added in version 1.2.0.

**Comment by slowdive14** [comment]
![image](https://user-images.githubusercontent.com/100013214/200447735-10279642-7a94-412f-bc76-336c9b6a5c22.png)

Thank you very much for the update reflecting my opinion.

However, I installed a new version and executed the command, but only two notes are visible. There are about 20 notebooks that I have issued so far.

**Comment by jonstodle** [comment]
The plugin only knows about the files listed in the data file, and it only removes files from the data file if you use the _Remove_ option. The plugin has no way of fetching previously published files from the web site.

It could be a sync issue if you're syncing files across multiple machines, but I'm not sure that applies to your situation.
