### ISSUE TITLE
Latex mathematical fomula rendering

### ISSUE THREAD

**Issue by SmithStarkHeu** [jonstodle/obsius-obsidian-plugin#8]
In the web I publish my notes, I find my latex fomula remian the origin markdown code.
![QG5KD3G34_5~N )JFJJZ$J1](https://user-images.githubusercontent.com/118436939/202430971-23ef77fe-de90-46db-aa72-ad3147d95bcf.png)

**Comment by jonstodle** [comment]
LaTeX rendering is included in the 2211.1 release, now rolling out
