### ISSUE TITLE
I keep getting "Failed to update" errors in Obsius 1.2.0

### ISSUE THREAD

**Issue by alentodorov** [jonstodle/obsius-obsidian-plugin#9]
I'm not able to edit or delete any existing notes. The errors are
`Failed to update note`
`Failed to remove note`

Publishing works fine.

**Comment by loogaru** [comment]
Still same issue

**Comment by qwepuorytgj** [comment]
same issue, still.

**Comment by skci** [comment]
Still same issue

**Comment by vitahlin** [comment]
Same issue

**Comment by HenMie** [comment]
The same.

**Comment by github770208646** [comment]
i want to know where is the note to be saved? is data safe?  how long can you keep this website?

**Comment by Lin-Ye-Ye** [comment]
Same issue

**Comment by jonstodle** [comment]
This issue should now be fixed in version 1.2.2

Sorry this has taken so long.
